# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 495846483f5789e68c51f89f35dc89d95d263697d759d68bc3d6af430ecbafbe2d10484461d9dd068d8578b8f41ebd50f9c242caf5a63289ffdebecb635a6f1b

test:
  secret_key_base: 837504a6c696a1cc5b0bcc56f35690c35c8e5d010547f96f17e7cc40914c7046db560a633e6dd45153ad20820bc3c3434e6e24d72afdb080dd529d751947a445

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
