# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3bab9de73228104bb65107698ee18506ecbbbe47e074f3aa54d32fbd3c7071e9e9eafd84ccea28baa8a35aa2b42bd93ecee19cb0259044403d20803d564a8bcd

test:
  secret_key_base: d0d14e0cd76a5f922156af16e290dc4b5f11270c9595c5fc40b190658b0cb1a4a4a3d1eac1f31bdf4bbb1e4f3419e388dffe78239e507193d2a3f1150a308421

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
